name: CI devops 2025 - Build and Push Docker Image
on:
  workflow_run:
    workflows: ["CI devops 2025 - Test Backend"]
    branches: [main]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to ForgeJo registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.FORGEJO_DOMAIN }}
          username: ${{ vars.FORGEJO_USERNAME }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      # Build and publish the container image for the API
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          tags: ${{ vars.FORGEJO_DOMAIN }}/${{ vars.FORGEJO_USERNAME }}/tp-devops-simple-api:latest
          push: true

      # Build and publish the container image for the database
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: ${{ vars.FORGEJO_DOMAIN }}/${{ vars.FORGEJO_USERNAME }}/tp-devops-database:latest
          push: true

      # Build and publish the container image for the HTTP server
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          tags: ${{ vars.FORGEJO_DOMAIN }}/${{ vars.FORGEJO_USERNAME }}/tp-devops-http-server:latest
          push: true

      # Build and publish the container image for the frontend
      - name: Build image and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./devops-front
          tags: ${{ vars.FORGEJO_DOMAIN }}/${{ vars.FORGEJO_USERNAME }}/tp-devops-frontend:latest
          push: true
