name: CI devops 2025 - Ansible
on:
  workflow_run:
    workflows: ["CI devops 2025 - Build and Push Docker Image"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v4
        with:
          playbook: playbook.yml
          directory: ./ansible/
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: --inventory inventories/setup.yml
