name: CI devops 2025
on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      # Retrieve the latest version of the repo
      - uses: actions/checkout@v4

      # Set up the environment to use afterward
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Run the tests with maven
      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: ./simple-api
