name: CI devops 2025
on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      # Retrieve the latest version of the repo
      - uses: actions/checkout@v4

      # Set up the environment to use afterward
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      # Run the tests with maven
      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: ./simple-api

      # Analyze with SonarQube
      - name: Analyze with SonarQube
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=ocineh_tp-devops-correction-docker -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: ./simple-api

  # Build and publish the containers images
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to ForgeJo registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.FORGEJO_DOMAIN }}
          username: ${{ vars.FORGEJO_USERNAME }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      # Build and publish the container image for the API
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          tags: ${{ vars.FORGEJO_DOMAIN }}/${{ vars.FORGEJO_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build and publish the container image for the database
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: ${{ vars.FORGEJO_DOMAIN }}/${{ vars.FORGEJO_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build and publish the container image for the HTTP server
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          tags: ${{ vars.FORGEJO_DOMAIN }}/${{ vars.FORGEJO_USERNAME }}/tp-devops-http-server:latest
          push: ${{ github.ref == 'refs/heads/main' }}
